/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { Float, useGLTF } from '@react-three/drei';

const PythonLogo = (props) => {
  const { nodes, materials } = useGLTF('models/python.glb');

  return (
    <Float floatIntensity={1}>
      <group position={[8, 8, 0]} scale={0.03} {...props} dispose={null}>
        <group scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Python_Python_0.geometry}
            material={materials.Python}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </Float>
  );
};

useGLTF.preload('models/python.glb');

export default PythonLogo;
